// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD07kLsCitvGYWpNHH3qkqYX-W6FnXBO0g',
    appId: '1:716140131825:web:48d2ef5cd7cb3c70f24050',
    messagingSenderId: '716140131825',
    projectId: 'homecontrol-85bc9',
    authDomain: 'homecontrol-85bc9.firebaseapp.com',
    storageBucket: 'homecontrol-85bc9.appspot.com',
    measurementId: 'G-0RBFNQKEKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq8aPPxYtUzVEMTkgAjgKIrsF-PvV1TJg',
    appId: '1:716140131825:android:a268f620a5b89883f24050',
    messagingSenderId: '716140131825',
    projectId: 'homecontrol-85bc9',
    storageBucket: 'homecontrol-85bc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVOLgfYFra8vEPd17s5xrKUoc6OtloiOk',
    appId: '1:716140131825:ios:599a51857c6de31bf24050',
    messagingSenderId: '716140131825',
    projectId: 'homecontrol-85bc9',
    storageBucket: 'homecontrol-85bc9.appspot.com',
    iosClientId: '716140131825-32g0n82ebmtet44i2k2g5mssaklbqiru.apps.googleusercontent.com',
    iosBundleId: 'com.example.monitorWater',
  );
}
